import {
  Portfolio1,
  Portfolio2,
  Portfolio3,
  Portfolio4,
  Portfolio5,
  Portfolio6,
  Portfolio7,
  Portfolio8,
  Portfolio9,
  Github,
  Tiktok,
  Linkedin,
} from "./assets";

export const portfolioData = [
  {
    title: "Pokémon Memory",
    thumbnail: Portfolio3,
    alt: "Pokémon Memory",
    category: "A memory game with the first gen pokémons",
    link: "https://memory-pokemon-dave.netlify.app/",
    link2: "https://github.com/DivineDragonDave/my-memory-game---pokemon",
    teknik: "HTML CSS JavaScript React Material-UI MongoDB",
  },
  {
    title: "Homemade Calendar",
    thumbnail: Portfolio2,
    alt: "a calendar",
    category: "Create your own calendar",
    link: "https://home-made-calendar.netlify.app/",
    link2: "https://github.com/DivineDragonDave/kalender",
    teknik: "HTML CSS JavaScript API",
  },
  {
    title: "Countries",
    thumbnail: Portfolio9,
    alt: "flags",
    category: "A site with info about countries",
    link: "https://countries-dave.netlify.app/",
    link2: "https://github.com/DivineDragonDave/contrys",
    teknik: "HTML CSS React Material-UI API",
  },

  {
    title: "Weather",
    thumbnail: Portfolio8,
    alt: "weather",
    category: "A simple weather app",
    link: "https://weather-app-dave.netlify.app/",
    link2: "https://github.com/DivineDragonDave/v-der-app",
    teknik: "HTML CSS JavaScript API",
  },

  {
    title: "Motivation",
    thumbnail: Portfolio4,
    alt: "motivation",
    category: "A generator for motivations",
    link: "https://motivationsgenerator.netlify.app/",
    link2: "https://github.com/DivineDragonDave/motivationsgenerator",
    teknik: "HTML CSS JavaScript API",
  },
  {
    title: "Quiz",
    thumbnail: Portfolio6,
    alt: "a quiz",
    category: "A simple quiz game",
    link: "https://dave-quiz.netlify.app/",
    link2: "https://github.com/DivineDragonDave/dave-quiz",
    teknik: "HTML CSS JavaScript",
  },
  {
    title: "Password Generator",
    thumbnail: Portfolio5,
    alt: "password gen",
    category: "A generator to get random text",
    link: "https://password-generator-dave.netlify.app/",
    link2: "https://github.com/DivineDragonDave/projekt-losenordsgenerator-4",
    teknik: "HTML CSS JavaScript",
  },
  {
    title: "Joke",
    thumbnail: Portfolio1,
    alt: "a joke",
    category: "A generator for jokes",
    link: "https://joke-generator-dave.netlify.app/",
    link2: "https://github.com/DivineDragonDave/jokegenerater",
    teknik: "HTML CSS JavaScript API",
  },
];

export const socials = [
  {
    name: "GitHub",
    icon: Github,
    alt: "follow me on GitHub",
    link: "https://github.com/DivineDragonDave",
  },
  {
    name: "Tiktok",
    icon: Tiktok,
    alt: "follow me on TikTok",
    link: "https://www.tiktok.com/@dave_maffia",
  },
  {
    name: "Linkedin",
    icon: Linkedin,
    alt: "follow me on LinkedIn",
    link: "https://www.linkedin.com/in/david-ribbfors/",
  },
];
